"""create parsed_file and deposition_attempt tables

Revision ID: 04416d171bbc
Revises:
Create Date: 2022-07-28 09:04:44.944476

"""
from alembic import op
import sqlalchemy as sa

from mecadoi.db import Yaml


# revision identifiers, used by Alembic.
revision = "04416d171bbc"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "parsed_file",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("path", sa.Text(), nullable=False),
        sa.Column("received_at", sa.DateTime(), nullable=False),
        sa.Column("manuscript", Yaml(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "deposition_attempt",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("id_parsed_file", sa.Integer(), nullable=True),
        sa.Column("deposition", sa.Text(), nullable=True),
        sa.Column("attempted_at", sa.DateTime(), nullable=True),
        sa.Column("succeeded", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["id_parsed_file"],
            ["parsed_file.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("deposition_attempt")
    op.drop_table("parsed_file")
    # ### end Alembic commands ###
