"""update manuscript yaml

Revision ID: 609ff12d1ef4
Revises: de760ff43a83
Create Date: 2025-08-08 14:40:13.711341

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = "609ff12d1ef4"
down_revision = "de760ff43a83"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        UPDATE parsed_file
        SET manuscript = REPLACE(manuscript, '!!python/object:src.', '!!python/object:mecadoi.')
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        UPDATE parsed_file
        SET manuscript = REPLACE(manuscript, '!!python/object:mecadoi.', '!!python/object:src.')
        """
    )
    # ### end Alembic commands ###
