"""added verification_failed column to deposition_attempt

Revision ID: 922d9e60c79c
Revises: 04416d171bbc
Create Date: 2022-07-28 09:07:23.164222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '922d9e60c79c'
down_revision = '04416d171bbc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deposition_attempt', sa.Column('verification_failed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deposition_attempt', 'verification_failed')
    # ### end Alembic commands ###
