"""added used_dois table

Revision ID: 9eb6389603c4
Revises: 922d9e60c79c
Create Date: 2022-07-28 14:12:20.998982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9eb6389603c4"
down_revision = "922d9e60c79c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "used_dois",
        sa.Column("doi", sa.Text(), nullable=False),
        sa.Column("resource", sa.Text(), nullable=False),
        sa.Column("claimed_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("doi"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("used_dois")
    # ### end Alembic commands ###
