"""Added status and doi fields to parsed_file table

Revision ID: c7a7fea7c678
Revises: 9eb6389603c4
Create Date: 2022-09-12 17:50:55.557937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c7a7fea7c678"
down_revision = "9eb6389603c4"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("parsed_file", sa.Column("doi", sa.Text(), nullable=True))
    op.add_column("parsed_file", sa.Column("status", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("parsed_file", "status")
    op.drop_column("parsed_file", "doi")
    # ### end Alembic commands ###
