"""Added status field to deposition_attempt table

Revision ID: de760ff43a83
Revises: c7a7fea7c678
Create Date: 2022-09-13 14:33:23.344085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "de760ff43a83"
down_revision = "c7a7fea7c678"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "deposition_attempt", sa.Column("status", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###
    op.execute("UPDATE deposition_attempt SET status=1 WHERE succeeded=1")
    op.execute("UPDATE deposition_attempt SET status=10 WHERE succeeded=0")
    op.execute("UPDATE deposition_attempt SET status=20 WHERE verification_failed=1")
    op.execute("UPDATE deposition_attempt SET status=21 WHERE deposition IS NULL")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("deposition_attempt", "status")
    # ### end Alembic commands ###
