from dotenv import load_dotenv
from os import getenv

load_dotenv()

DEPOSITOR_NAME = getenv('DEPOSITOR_NAME')
DEPOSITOR_EMAIL = getenv('DEPOSITOR_EMAIL')
REGISTRANT_NAME = getenv('REGISTRANT_NAME')
INSTITUTION_NAME = getenv('INSTITUTION_NAME')
RESOURCE_URL_TEMPLATE = getenv('RESOURCE_URL_TEMPLATE')

DOI_DB_FILE = getenv('DOI_DB_FILE')
DOI_DB_WARNING_THRESHOLD = int(getenv('DOI_DB_WARNING_THRESHOLD'))

CROSSREF_DEPOSITION_URL = getenv('CROSSREF_DEPOSITION_URL')
CROSSREF_USERNAME = getenv('CROSSREF_USERNAME')
CROSSREF_PASSWORD = getenv('CROSSREF_PASSWORD')
