name: Build & deploy documentation

on:
 push:
   branches:
    - main

jobs:
 build-and-deploy:
   runs-on: ubuntu-latest
   steps:
   - uses: actions/setup-python@v4
     with:
       python-version: "3.9"
   - uses: actions/checkout@v3
     with:
       fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
   - name: Build and Commit
     uses: sphinx-notes/pages@v2
     with:
       requirements_path: "./requirements/docs.txt"
   - name: Push changes
     uses: ad-m/github-push-action@master
     with:
       github_token: ${{ secrets.GITHUB_TOKEN }}
       branch: gh-pages
